[package]
name = "beeline"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6"
benimator = "2.0"
impacted = { version = "1.3", features = ["bevy-06"] }
rand = "0.8"
strum = "0.24"
strum_macros = "0.24"
